services:
  postgres:
    image: postgres:16
    container_name: mechanic-ai-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mechanic-ai-nextjs
    restart: always
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      NODE_ENV: production
      GOOGLE_GENERATIVE_AI_API_KEY: ${GOOGLE_GENERATIVE_AI_API_KEY}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
    networks:
      - internal
    ports:
      - "3000:3000"  # expose only to host so nginx can reach it

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
